### ISSUE TITLE
Gotchas

### ISSUE THREAD

**Issue by coolacid** [logstash-plugins/logstash-codec-cef#1]
CEF is a horrible, horrible format.

Need to be able to handle encoding in encode and decode:
- pipe (|)
- backslash (\)
- equals (=)

In the decode, someone thought it would be a good idea to not use quotes. So:

filename=This is a filename.txt fsize=100 

is totally valid.

**Comment by colinsurprenant** [comment]
trying to asses the importance and severity of this very old issue, @coolacid can you provide details on the exactly what is affected by the encoding problem you reported? does that break in specific cases?

**Comment by breml** [comment]
@colinsurprenant In the CEF spec is defined, how to handle the character (e.g. |, =, \), used by the protocol (escaping). The current implementation does not handle the character encoding correctly. I pushed a PR #21, which addresses these issues. But as I mentioned in my commit message, the CEF format may not by processed with regex alone. To catch all edge cases, a small parser should be written.

**Comment by t1nkerer** [comment]
Hello,

I have dealt with LEEF log format which looks exactly the same and there you have fields separated with <TAB>. Is it not the case with CEF?

https://www.ibm.com/developerworks/community/wikis/form/anonymous/api/wiki/9989d3d7-02c1-444e-92be-576b33d2f2be/page/3dc63f46-4a33-4e0b-98bf-4e55b74e556b/attachment/a19b9122-5940-4c89-ba3e-4b4fc25e2328/media/QRadar_LEEF_Format_Guide.pdf

**Comment by breml** [comment]
Hi @t1nkerer
I don't know the LEEF format and how similar it is to CEF. Maybe you want to have a look into the CEF specification your self: https://www.protect724.hpe.com/docs/DOC-1072
