### ISSUE TITLE
elasticsearch index template

### ISSUE THREAD

**Issue by robellison** [logstash-plugins/logstash-codec-cef#23]
not so much an issue,  but is there by any chance an associated index template for when this is used before the elasticsearch output plugin?
at the moment everything is a string

**Comment by breml** [comment]
@robellison if I understand your question correctly, you are using the cef codec on an input plugin, where you are receiving data in cef format, correct? If this is the case, you may convert the values by using a mutate filter (https://www.elastic.co/guide/en/logstash/current/plugins-filters-mutate.html#plugins-filters-mutate-convert) like this:

```
filter {
  mutate {
    convert => { "fieldname" => "integer" }
  }
}
```

With this convertion `fieldname` will be converted to an numeric value and is therefore saved as such in elasticsearch.

**Comment by robellison** [comment]
i meant more on the elasticsearch index side.
i've sorted it now.. see attached if anyone wants to use it
[cef_mapper.txt](https://github.com/logstash-plugins/logstash-codec-cef/files/318941/cef_mapper.txt)

**Comment by breml** [comment]
@robellison if your problem is solved, would you mind to close this issue?

**Comment by s-beltran-miranda** [comment]
@robellison I was wondering how did you go about implementing the template file?

**Comment by robellison** [comment]
assuming you want to call it cef_template and the txt file you've renamed to cef_mapper.json
just do this:
 curl -XPOST 'http://localhost:9200/_template/cef_template' -d @cef_mapper.json

any new indexes called cef* will use that template
