### ISSUE TITLE
Tag parsing failures instead of throwing an exception

### ISSUE THREAD

**Issue by jsvd** [logstash-plugins/logstash-codec-cef#25]
Like the json codec, this one should gracefully tag an event with parse failure if the payload isn't a proper cef formatted string.

**Comment by breml** [comment]
Relevant code from json code: https://github.com/logstash-plugins/logstash-codec-json/blob/e4fe6047a173119081180b4ee74bef1bd8695bb1/lib/logstash/codecs/json.rb#L49-L51
