### ISSUE TITLE
optionally keep raw data in the event

### ISSUE THREAD

**Issue by jsvd** [logstash-plugins/logstash-codec-cef#34]
I'm not sure how valuable this is to the general population, but [in this issue](https://github.com/elastic/logstash/issues/6932#issuecomment-295164799) there was a request to keep the raw data before the parsing in the event itself.

This is easy to implement with an option like `:raw_data_field => "field_string"` that defaults to null but if set will store the raw data in that field.

**Comment by kmcgerald** [comment]
This would be useful to allow logstash to forward the original message on to another destination.
