### ISSUE TITLE
Link to CEF specification in documentation is not working

### ISSUE THREAD

**Issue by breml** [logstash-plugins/logstash-codec-cef#40]
Link  https://protect724.hp.com/servlet/JiveServlet/downloadBody/1072-102-6-4697/CommonEventFormat.pdf is dead.

**Comment by nich07as** [comment]
Resolved in [PR#38](https://github.com/logstash-plugins/logstash-codec-cef/pull/38)

**Comment by nich07as** [comment]
FWIW, the link is [here](https://community.saas.hpe.com/dcvta86296/attachments/dcvta86296/connector-documentation/1116/1/CommonEventFormatv23.pdf) and I've updated it in the PR mentioned above. ~N

**Comment by breml** [comment]
`docs/index.asciidoc` needs to be updated as well.

**Comment by nich07as** [comment]
Sorry @breml forgot about the asciidoc, fixed in #42

**Comment by breml** [comment]
Fixed in #41 and #42

**Comment by MarkUlmer** [comment]
Latest correct link is here: https://community.softwaregrp.com/t5/ArcSight-Connectors/ArcSight-Common-Event-Format-CEF-Implementation-Standard/ta-p/1645557
