### ISSUE TITLE
need to improve installation instrctions

### ISSUE THREAD

**Issue by agonen** [logstash-plugins/logstash-codec-cef#5]
I'm trying to compile logstash-codec-cef.

I've pull the git rep an when doing : 
vagrant@elk:~/logstash-codec-cef$ make tarball
make: *** No rule to make target `tarball'.  Stop.

when I've tried to do :
vagrant@elk:~/logstash-codec-cef$ make tarball
make: *** No rule to make target `tarball'.  Stop.

**Comment by laf-rge** [comment]
Yep this has something to do with the new style plugins. I'm a ruby n00b so I can't say anything other than I can't contribute my fork until someone updates the instructions.

**Comment by laf-rge** [comment]
Minor google fu and I found this interesting link https://github.com/logstash-plugins/logstash-output-elasticsearch/pull/18#issuecomment-63520712

**Comment by jsvd** [comment]
yep, so now you can test it w/ jruby using `bundle install && bundle exec rspec`

**Comment by jsvd** [comment]
installation instructions have been updated and no longer refer to stuff like "make tarball", closing.
