### ISSUE TITLE
CEF codec error

### ISSUE THREAD

**Issue by Betsworth22** [logstash-plugins/logstash-codec-cef#6]
bin/logstash --configtest --config /etc/logstash/conf.d/test.conf
The error reported is:
  cef must set a milestone. For more information about plugin milestones, see http://logstash.net/docs/1.5.0.beta1/plugin-milestone

The install went fine but I can't seem to get logstash started with the codec setup on a file input. Any assistance or guidance is appreciated. Thanks.

**Comment by coolacid** [comment]
Milestones are going away in next version of logstash. You can add milestone to the .rb file, or wait for the next release of 1.5.x.
