### ISSUE TITLE
Incorrect CEF field mapping

### ISSUE THREAD

**Issue by n3g** [logstash-plugins/logstash-codec-cef#62]
Hi all,

The CEF codec has an incorrect mapping for the "ahost" field.
It's currently mapping to "agentHost":
https://github.com/logstash-plugins/logstash-codec-cef/blob/559f7e5f3505cb143939ab5be479814bf3d1e2f6/lib/logstash/codecs/cef.rb#L156

But according to the CEF documentation the correct mapping is "agentHostName":

`ahost | agentHostName | String | 1023 | The hostname of the ArcSight connector that processed the event.`

Not sure if I should submit a pull request, but I'm reporting it first.

Best,
Ricardo.

**Comment by colinsurprenant** [comment]
Fixed by #62 and v6.1.0 published with the fix.
