### ISSUE TITLE
Old link to CEF implementation standard in documentation

### ISSUE THREAD

**Issue by P1llus** [logstash-plugins/logstash-codec-cef#66]
The domains have changed for the documentation, and certain old documentation has been removed. The current link on: https://www.elastic.co/guide/en/logstash/current/plugins-codecs-cef.html is directing to a very old revision from 2013 which is now broken:
https://community.saas.hpe.com/dcvta86296/attachments/dcvta86296/connector-documentation/1116/1/CommonEventFormatv23.pdf

Currently only the newer revision is available publicly, which is this one, dated sept 2017:

https://community.microfocus.com/t5/ArcSight-Connectors/ArcSight-Common-Event-Format-CEF-Implementation-Standard/ta-p/1645557?attachment-id=68077

Is there a way to reference the new revision in any way?

**Comment by consulthys** [comment]
This is still not resolved and the [link is still broken](https://www.elastic.co/guide/en/logstash/current/plugins-codecs-cef.html#_description_164)

**Comment by karenzone** [comment]
Should be resolved with the merge/publish of #97. 
@P1llus, thank you for filing this issue. @consulthys, thank you for bumping to raise visibility.
