### ISSUE TITLE
non-alphanumeric extension field names not parsing as expected

### ISSUE THREAD

**Issue by kvmuralidhar** [logstash-plugins/logstash-codec-cef#67]
Hi,

The additional key value pairs are not mapped correctly and causing the doc not to be indexed into elasticsearch.   The issue is similar to the other issue opened by "errantpixel" and in my case the ad field is not two characters.  I have also defined explicit mappings for the additional data fields.

Here is the sample data

CEF:0|MyVendor|MyProduct|13.1.1|200000152|xml tag (Parameter)|Medium| eventId=553981669 externalId=4757303752018785083 msg=N/A app=HTTPS art=1551709130614 deviceSeverity=5 act=blocked rt=1551680329000 src=10.10.10.10 spt=56592 _cefVer=0.1 ad.Authorization=Bearer ad.X-AutoDiscoverArchiveAsSmtp=true ad.wm__client__ip=73.222.35.141 ad.<?xml_,version_~\"1.0\"_,encoding_~\"UTF-8\"?><Autodiscover_,xmlns_~\"http://schemas.microsoft.com/exchange/autodiscover/outlook/requestschema/2006\"><Request><EMailAddress>PFPMBHO43@mydomain.com</EMailAddress><AcceptableResponseSchema>http=//schemas.microsoft.com/exchange/autodiscover/outlook/responseschema/2006a</AcceptableResponseSchema></Request></Autodiscover> ad.Connection=keep-alive ad.X-User-Identity=PFPMMM@mydomain.com ad.Accept-Language=en ad.Content-Length=354 ad.Request-Id={891EE72D-CAB4-403A-A66D-96C1163376EC} ad.X-ClientStatistics=DeviceID\\=AB942512-6A7C-5316-81AF-4876E3C508C8; SessionID\\=9E9339F7-5F03-45A9-879F-BA13827B47D0 ad.X-MyVendor-Forwarder=l-tier1c aid=39xymmWgBABCABexAeCkPBg\\=\\=

Error as per the log is

failed to parse field [ad.wm__client__ip] of type [ip]", "caused_by"=>{"type"=>"illegal_argument_exception", "reason"=>"'73.222.35.141 ad.<?xml_,version_~\"1.0\"_,encoding_~\"UTF-8\"?><Autodiscover_,xmlns_~\"http://schemas.microsoft.com/exchange/autodiscover/outlook/requestschema/2006\"><Request><EMailAddress>PFPMBHO43@mydomain.com</EMailAddress><AcceptableResponseSchema>http=//schemas.microsoft.com/exchange/autodiscover/outlook/responseschema/2006a</AcceptableResponseSchema></Request></Autodiscover> ad.Connection=keep-alive' is not an IP string literal.

I took a look at the CEF parser (arcsight) and it looks like the parser is breaking on line 203 and 215 (with version 6.6.1).

EXTENSION_KEY_PATTERN = /(?:\w+(?:\.[^\s]\w+[^\|\s\.\=\\]+)?(?==))/

EXTENSION_VALUE_PATTERN = /(?:\S|\s++(?!#{EXTENSION_KEY_PATTERN}=))*/

Thanks
Murali

**Comment by kvmuralidhar** [comment]
Hi,

By changing the EXTENSION_KEY_PATTERN to (?:\w+(?:\.[^\s]\S+[^\|\s\.\=\\]+)?(?==)), the parser is now matching the keys (field names) correctly.  The error I am getting now is better then before.

failed to parse field [ad.wm__client__ip] of type [ip]", "caused_by"=>{"type"=>"illegal_argument_exception", "reason"=>"'161.167.229.15 ad.' is not an IP string literal.

Thanks
Murali

**Comment by kvmuralidhar** [comment]
Hi,

The keys are now matched correctly after I changed the EXTENSION_KEY_PATTERN to (?:\w+(?:\.[^\s]\S+[^\|\s\.\=\\]+)?(?==)).  The error in the logstash logs is as follows.

failed to parse field [ad.wm__client__ip] of type [ip]", "caused_by"=>{"type"=>"illegal_argument_exception", "reason"=>"'161.167.229.15 ad.' is not an IP string literal.

Thanks
Murali

**Comment by yaauie** [comment]
The CEF Codec is failing to identify the following string as an extension field key because according to the CEF specification, it is _not_ a valid key and therefore the parser _must_ treat it as a continuation of the prior extension field's value; the input is invalid and the parser is behaving as-specified.

~~~
ad.<Autodiscover,xmlns_~"http://schemas.microsoft.com/exchange/autodiscover/outlook/requestschema/2006\">PFPMBHO43@mydomain.comhttp
~~~

CEF Extension Field names are constrained by the CEF specification:

> ### Requirements
> Custom extension names should meet the following requirements. Custom extension nam(s):
> •Must be made up of a single word, with no spaces.
> •Must be alphanumeric
> •Should be as clear and concise as possible.
> •May not be named the same as any name listed in ArcSight Extension Dictionary.
>
> -- [Implementing ArcSight Common Event Format (CEF) - Version 25](https://community.microfocus.com/t5/ArcSight-Connectors/ArcSight-Common-Event-Format-CEF-Implementation-Standard/ta-p/1645557?attachment-id=68077)

Notably, the provided extension field name is neither "a single word" nor "alphanumeric". Arguably it is also not "as clear and concise as possible" either.

***

I do not presently have a way to configure the CEF parser in such a way that it will decode this malformed message in the way that you expect while still continuing to parse all valid CEF inputs as specified. It may be possible to design a patch in such a way that a user can _opt-in_ to the codec handling a certain subset of illegal inputs in a certain way, but doing so overreaches the specification and is liable to have edge-cases that cause syntactically-legal CEF be parsed incorrectly.

**Comment by kvmuralidhar** [comment]
Hi Yaauie,

Thanks for the explanation and I understand that the field wasn't properly formatted.  The custom extension fields are properly formatted in the source now but I am still seeing issues with the indexed event.  Here is an example.  

the CEF parser is merging the values into 1 field instead of creating three different fields.  The field names displayed here meets the CEF field requirements.

"ad.Cache-Control": "no-cache ad.X-User-Identity=Deanna.Decourcy@domain.com ad.X-FeatureVersion=1"

"ad.Cache-Control"
"ad.X-User-Identity"
ad.X-FeatureVersion

Thanks
Murali

**Comment by yaauie** [comment]
While I understand that you would like to use the following extension field names, they are problematic.

~~~
ad.Cache-Control
ad.X-User-Identity
ad.X-FeatureVersion
~~~

None of the above are valid extension field names per the spec; each of them is nether "alphanumeric" (i.e., entirely composed of characters in the _alphabetic_ and _numeric_ sets) nor "a single word" (i.e., devoid of spaces or breaking punctuation).

***

Again, it may be possible to design an opt-in feature to allow the parser to be more lenient in such a way that it parses this particular class of invalid input as you expect. Doing so carries the risk of handling certain classes of syntactically-legal CEF incorrectly, and therefore must be an opt-in feature with appropriate caveats.

**Comment by kvmuralidhar** [comment]
Hi Yaauie,

Thanks again for the clarification :-). 

Thanks
Murali
